version: '3'
services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: always
  socket:
    build: 
      context: ./socket-server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
  client:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    restart: always